-- MySQL Script generated by MySQL Workbench
-- Fri May 17 21:58:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema crud_java
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crud_java
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crud_java` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `crud_java` ;

-- -----------------------------------------------------
-- Table `crud_java`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crud_java`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Idade` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Dados Gerados Via ChatGPT 

INSERT INTO `usuarios` (`id`, `Nome`, `Email`, `Idade`) VALUES
(1, 'Ana Silva', 'ana.silva@example.com', '28'),
(2, 'Bruno Costa', 'bruno.costa@example.com', '34'),
(3, 'Carla Mendes', 'carla.mendes@example.com', '22'),
(4, 'Daniel Souza', 'daniel.souza@example.com', '31'),
(5, 'Eduardo Lima', 'eduardo.lima@example.com', '25'),
(6, 'Fernanda Alves', 'fernanda.alves@example.com', '27'),
(7, 'Gustavo Pereira', 'gustavo.pereira@example.com', '30'),
(8, 'Helena Martins', 'helena.martins@example.com', '29'),
(9, 'Igor Rocha', 'igor.rocha@example.com', '23'),
(10, 'Juliana Duarte', 'juliana.duarte@example.com', '26'),
(11, 'Karla Ferreira', 'karla.ferreira@example.com', '24'),
(12, 'Lucas Barbosa', 'lucas.barbosa@example.com', '32'),
(13, 'Mariana Gomes', 'mariana.gomes@example.com', '28'),
(14, 'Nicolas Fernandes', 'nicolas.fernandes@example.com', '33'),
(15, 'Olivia Castro', 'olivia.castro@example.com', '27'),
(16, 'Paulo Ribeiro', 'paulo.ribeiro@example.com', '35'),
(17, 'Quésia Moraes', 'quesia.moraes@example.com', '24'),
(18, 'Ricardo Araujo', 'ricardo.araujo@example.com', '30'),
(19, 'Sofia Nascimento', 'sofia.nascimento@example.com', '22'),
(20, 'Thiago Cardoso', 'thiago.cardoso@example.com', '31'),
(21, 'Ursula Dias', 'ursula.dias@example.com', '26'),
(22, 'Victor Figueiredo', 'victor.figueiredo@example.com', '29'),
(23, 'Wesley Santana', 'wesley.santana@example.com', '28'),
(24, 'Xavier Cunha', 'xavier.cunha@example.com', '32'),
(25, 'Yara Silveira', 'yara.silveira@example.com', '23'),
(26, 'Zeca Moura', 'zeca.moura@example.com', '34'),
(27, 'Alice Carvalho', 'alice.carvalho@example.com', '22'),
(28, 'Bruno Santos', 'bruno.santos@example.com', '33'),
(29, 'Carolina Rocha', 'carolina.rocha@example.com', '27'),
(30, 'Diego Ferreira', 'diego.ferreira@example.com', '31'),
(31, 'Eduarda Lima', 'eduarda.lima@example.com', '25'),
(32, 'Felipe Alves', 'felipe.alves@example.com', '29'),
(33, 'Gabriela Martins', 'gabriela.martins@example.com', '26'),
(34, 'Heitor Pereira', 'heitor.pereira@example.com', '28'),
(35, 'Isabela Duarte', 'isabela.duarte@example.com', '24'),
(36, 'João Barbosa', 'joao.barbosa@example.com', '32'),
(37, 'Larissa Gomes', 'larissa.gomes@example.com', '30'),
(38, 'Marcos Fernandes', 'marcos.fernandes@example.com', '27'),
(39, 'Natália Castro', 'natalia.castro@example.com', '25'),
(40, 'Otávio Ribeiro', 'otavio.ribeiro@example.com', '33'),
(41, 'Patrícia Moraes', 'patricia.moraes@example.com', '24'),
(42, 'Renato Araujo', 'renato.araujo@example.com', '31'),
(43, 'Sérgio Nascimento', 'sergio.nascimento@example.com', '28'),
(44, 'Tamires Cardoso', 'tamires.cardoso@example.com', '26'),
(45, 'Valentina Dias', 'valentina.dias@example.com', '23'),
(46, 'Wagner Figueiredo', 'wagner.figueiredo@example.com', '32'),
(47, 'Ximena Santana', 'ximena.santana@example.com', '29'),
(48, 'Yuri Cunha', 'yuri.cunha@example.com', '27'),
(49, 'Zélia Silveira', 'zelia.silveira@example.com', '31'),
(50, 'Amanda Carvalho', 'amanda.carvalho@example.com', '22'),
(51, 'Brenda Santos', 'brenda.santos@example.com', '30'),
(52, 'Camila Rocha', 'camila.rocha@example.com', '25'),
(53, 'Davi Ferreira', 'davi.ferreira@example.com', '29'),
(54, 'Eduardo Lima', 'eduardo.lima2@example.com', '26'),
(55, 'Fernanda Alves', 'fernanda.alves2@example.com', '31'),
(56, 'Guilherme Martins', 'guilherme.martins@example.com', '28'),
(57, 'Helena Pereira', 'helena.pereira@example.com', '24'),
(58, 'Isabel Duarte', 'isabel.duarte@example.com', '32'),
(59, 'Julio Barbosa', 'julio.barbosa@example.com', '27'),
(60, 'Letícia Gomes', 'leticia.gomes@example.com', '29'),
(61, 'Marcelo Fernandes', 'marcelo.fernandes@example.com', '30'),
(62, 'Nina Castro', 'nina.castro@example.com', '25'),
(63, 'Otávio Ribeiro', 'otavio.ribeiro2@example.com', '33'),
(64, 'Paula Moraes', 'paula.moraes@example.com', '22'),
(65, 'Rafael Araujo', 'rafael.araujo@example.com', '26'),
(66, 'Sofia Nascimento', 'sofia.nascimento2@example.com', '28'),
(67, 'Tiago Cardoso', 'tiago.cardoso@example.com', '31'),
(68, 'Vitor Dias', 'vitor.dias@example.com', '24'),
(69, 'Weslley Figueiredo', 'weslley.figueiredo@example.com', '30'),
(70, 'Xuxa Santana', 'xuxa.santana@example.com', '32'),
(71, 'Yasmin Cunha', 'yasmin.cunha@example.com', '27'),
(72, 'Zeca Moura', 'zeca.moura2@example.com', '29'),
(73, 'Ana Carvalho', 'ana.carvalho@example.com', '28'),
(74, 'Bruno Santos', 'bruno.santos2@example.com', '34'),
(75, 'Carlos Rocha', 'carlos.rocha@example.com', '22'),
(76, 'Daniel Ferreira', 'daniel.ferreira@example.com', '31'),
(77, 'Elisa Lima', 'elisa.lima@example.com', '25'),
(78, 'Fernando Alves', 'fernando.alves@example.com', '27'),
(79, 'Gabriel Martins', 'gabriel.martins@example.com', '30'),
(80, 'Heloísa Pereira', 'heloisa.pereira@example.com', '29'),
(81, 'Igor Duarte', 'igor.duarte@example.com', '23'),
(82, 'Júlia Barbosa', 'julia.barbosa@example.com', '26'),
(83, 'Kleber Gomes', 'kleber.gomes@example.com', '24'),
(84, 'Luciana Fernandes', 'luciana.fernandes@example.com', '32'),
(85, 'Matheus Castro', 'matheus.castro@example.com', '28'),
(86, 'Nathalia Ribeiro', 'nathalia.ribeiro@example.com', '33'),
(87, 'Osvaldo Moraes', 'osvaldo.moraes@example.com', '27'),
(88, 'Pedro Araujo', 'pedro.araujo@example.com', '35'),
(89, 'Raquel Nascimento', 'raquel.nascimento@example.com', '24'),
(90, 'Sandro Cardoso', 'sandro.cardoso@example.com', '30'),
(91, 'Talita Dias', 'talita.dias@example.com', '22'),
(92, 'Vanessa Figueiredo', 'vanessa.figueiredo@example.com', '28'),
(93, 'William Santana', 'william.santana@example.com', '34'),
(94, 'Xandão Cunha', 'xandao.cunha@example.com', '26'),
(95, 'Yone Silveira', 'yone.silveira@example.com', '31'),
(96, 'Zilda Carvalho', 'zilda.carvalho@example.com', '23'),
(97, 'Adriana Santos', 'adriana.santos@example.com', '29'),
(98, 'Bernardo Rocha', 'bernardo.rocha@example.com', '32'),
(99, 'Cecília Ferreira', 'cecilia.ferreira@example.com', '24'),
(100, 'Denis Lima', 'denis.lima@example.com', '30'),
(101, 'Eliana Alves', 'eliana.alves@example.com', '27'),
(102, 'Fábio Martins', 'fabio.martins@example.com', '31'),
(103, 'Graça Pereira', 'graca.pereira@example.com', '26'),
(104, 'Henrique Duarte', 'henrique.duarte@example.com', '29'),
(105, 'Iara Barbosa', 'iara.barbosa@example.com', '25'),
(106, 'Joana Gomes', 'joana.gomes@example.com', '28'),
(107, 'Kelvin Fernandes', 'kelvin.fernandes@example.com', '30'),
(108, 'Larissa Castro', 'larissa.castro@example.com', '23'),
(109, 'Mauro Ribeiro', 'mauro.ribeiro@example.com', '32'),
(110, 'Nélson Moraes', 'nelson.moraes@example.com', '24'),
(111, 'Otávio Araujo', 'otavio.araujo@example.com', '34'),
(112, 'Patrícia Nascimento', 'patricia.nascimento@example.com', '27'),
(113, 'Roberto Cardoso', 'roberto.cardoso@example.com', '31'),
(114, 'Samara Dias', 'samara.dias@example.com', '28'),
(115, 'Tadeu Figueiredo', 'tadeu.figueiredo@example.com', '29'),
(116, 'Vera Santana', 'vera.santana@example.com', '30'),
(117, 'Wendel Cunha', 'wendel.cunha@example.com', '32'),
(118, 'Xenia Silveira', 'xenia.silveira@example.com', '23'),
(119, 'Yago Carvalho', 'yago.carvalho@example.com', '24'),
(120, 'Zoraide Santos', 'zoraide.santos@example.com', '25'),
(121, 'Alan Rocha', 'alan.rocha@example.com', '29'),
(122, 'Bárbara Ferreira', 'barbara.ferreira@example.com', '28'),
(123, 'Carlos Lima', 'carlos.lima@example.com', '30'),
(124, 'Diana Alves', 'diana.alves@example.com', '27'),
(125, 'Eduardo Martins', 'eduardo.martins@example.com', '26'),
(126, 'Fernanda Pereira', 'fernanda.pereira@example.com', '31'),
(127, 'Gustavo Duarte', 'gustavo.duarte@example.com', '24'),
(128, 'Hélio Barbosa', 'helio.barbosa@example.com', '32'),
(129, 'Isis Gomes', 'isis.gomes@example.com', '25'),
(130, 'Jonas Fernandes', 'jonas.fernandes@example.com', '29'),
(131, 'Karen Castro', 'karen.castro@example.com', '30'),
(132, 'Lucas Ribeiro', 'lucas.ribeiro@example.com', '28'),
(133, 'Mariana Moraes', 'mariana.moraes@example.com', '22'),
(134, 'Natalia Araujo', 'natalia.araujo@example.com', '31'),
(135, 'Otto Nascimento', 'otto.nascimento@example.com', '27'),
(136, 'Paulo Cardoso', 'paulo.cardoso@example.com', '33'),
(137, 'Renata Dias', 'renata.dias@example.com', '24'),
(138, 'Sérgio Figueiredo', 'sergio.figueiredo@example.com', '29'),
(139, 'Thais Santana', 'thais.santana@example.com', '28'),
(140, 'Vicente Cunha', 'vicente.cunha@example.com', '31'),
(141, 'Wesley Silveira', 'wesley.silveira@example.com', '26'),
(142, 'Xuxa Carvalho', 'xuxa.carvalho@example.com', '32'),
(143, 'Yasmin Santos', 'yasmin.santos@example.com', '25'),
(144, 'Zuleika Rocha', 'zuleika.rocha@example.com', '23'),
(145, 'Aline Ferreira', 'aline.ferreira@example.com', '27'),
(146, 'Bruno Lima', 'bruno.lima@example.com', '30'),
(147, 'Carmen Alves', 'carmen.alves@example.com', '28'),
(148, 'Diego Martins', 'diego.martins@example.com', '31'),
(149, 'Ester Pereira', 'ester.pereira@example.com', '26'),
(150, 'Fábio Duarte', 'fabio.duarte@example.com', '29');
