-- MySQL Script generated by MySQL Workbench
-- Fri May 17 21:58:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema crud_java
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crud_java
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crud_java` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `crud_java` ;

-- -----------------------------------------------------
-- Table `crud_java`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crud_java`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Idade` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `usuarios` (`id`,`Nome`,`Email`,`Idade`) VALUES (1,'Italo Gabriel','italo044704@ceuma.com.br','24');
INSERT INTO `usuarios` (`id`,`Nome`,`Email`,`Idade`) VALUES (2,'Telasko Pinto ','telaskopinto@gmail.com','35');
INSERT INTO `usuarios` (`id`,`Nome`,`Email`,`Idade`) VALUES (3,'Takamassa Nomuro ','takamassanomuro@gmail.com','46');
INSERT INTO `usuarios` (`id`,`Nome`,`Email`,`Idade`) VALUES (4,'Giuseppe Kadura ','giuseppekadura@gmail.com','74');
INSERT INTO `usuarios` (`id`,`Nome`,`Email`,`Idade`) VALUES (5,'Fuderu Kamiyamoto ','fuderukamiyamoto@gmail.com','34');
INSERT INTO `usuarios` (`id`,`Nome`,`Email`,`Idade`) VALUES (6,'Al’Beel Brah-Ga','abeelbraga@gmail.com','68');
INSERT INTO `usuarios` (`id`,`Nome`,`Email`,`Idade`) VALUES (7,'Hermano Menezes','hermanomenezes@gmail.com','48');
INSERT INTO `usuarios` (`id`,`Nome`,`Email`,`Idade`) VALUES (8,'Adyul Son Batysta','adylsonbatysta@gmail.com','65');
