-- MySQL Script generated by MySQL Workbench
-- Fri May 17 21:58:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema crud_java
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crud_java
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crud_java` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `crud_java` ;

-- -----------------------------------------------------
-- Table `crud_java`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crud_java`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Idade` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Dados Gerados Via ChatGPT 

INSERT INTO `usuarios` (`id`, `Nome`, `Email`, `Idade`) VALUES
(1, 'Ana Silva', 'ana.silva@example.com', '20/05/1996'),
(2, 'Bruno Costa', 'bruno.costa@example.com', '20/05/1990'),
(3, 'Carla Mendes', 'carla.mendes@example.com', '20/05/2002'),
(4, 'Daniel Souza', 'daniel.souza@example.com', '20/05/1993'),
(5, 'Eduardo Lima', 'eduardo.lima@example.com', '20/05/1999'),
(6, 'Fernanda Alves', 'fernanda.alves@example.com', '20/05/1997'),
(7, 'Gustavo Pereira', 'gustavo.pereira@example.com', '20/05/1994'),
(8, 'Helena Martins', 'helena.martins@example.com', '20/05/1995'),
(9, 'Igor Rocha', 'igor.rocha@example.com', '20/05/2001'),
(10, 'Juliana Duarte', 'juliana.duarte@example.com', '20/05/1998'),
(11, 'Karla Ferreira', 'karla.ferreira@example.com', '20/05/2000'),
(12, 'Lucas Barbosa', 'lucas.barbosa@example.com', '20/05/1992'),
(13, 'Mariana Gomes', 'mariana.gomes@example.com', '20/05/1996'),
(14, 'Nicolas Fernandes', 'nicolas.fernandes@example.com', '20/05/1991'),
(15, 'Olivia Castro', 'olivia.castro@example.com', '20/05/1997'),
(16, 'Paulo Ribeiro', 'paulo.ribeiro@example.com', '20/05/1989'),
(17, 'Quésia Moraes', 'quesia.moraes@example.com', '20/05/2000'),
(18, 'Ricardo Araujo', 'ricardo.araujo@example.com', '20/05/1994'),
(19, 'Sofia Nascimento', 'sofia.nascimento@example.com', '20/05/2002'),
(20, 'Thiago Cardoso', 'thiago.cardoso@example.com', '20/05/1993'),
(21, 'Ursula Dias', 'ursula.dias@example.com', '20/05/1998'),
(22, 'Victor Figueiredo', 'victor.figueiredo@example.com', '20/05/1995'),
(23, 'Wesley Santana', 'wesley.santana@example.com', '20/05/1996'),
(24, 'Xavier Cunha', 'xavier.cunha@example.com', '20/05/1992'),
(25, 'Yara Silveira', 'yara.silveira@example.com', '20/05/2001'),
(26, 'Zeca Moura', 'zeca.moura@example.com', '20/05/1990'),
(27, 'Alice Carvalho', 'alice.carvalho@example.com', '20/05/2002'),
(28, 'Bruno Santos', 'bruno.santos@example.com', '20/05/1991'),
(29, 'Carolina Rocha', 'carolina.rocha@example.com', '20/05/1997'),
(30, 'Diego Ferreira', 'diego.ferreira@example.com', '20/05/1993'),
(31, 'Eduarda Lima', 'eduarda.lima@example.com', '20/05/1999'),
(32, 'Felipe Alves', 'felipe.alves@example.com', '20/05/1995'),
(33, 'Gabriela Martins', 'gabriela.martins@example.com', '20/05/1998'),
(34, 'Heitor Pereira', 'heitor.pereira@example.com', '20/05/1996'),
(35, 'Isabela Duarte', 'isabela.duarte@example.com', '20/05/2000'),
(36, 'João Barbosa', 'joao.barbosa@example.com', '20/05/1992'),
(37, 'Larissa Gomes', 'larissa.gomes@example.com', '20/05/1994'),
(38, 'Marcos Fernandes', 'marcos.fernandes@example.com', '20/05/1997'),
(39, 'Natália Castro', 'natalia.castro@example.com', '20/05/1999'),
(40, 'Otávio Ribeiro', 'otavio.ribeiro@example.com', '20/05/1991'),
(41, 'Patrícia Moraes', 'patricia.moraes@example.com', '20/05/2000'),
(42, 'Renato Araujo', 'renato.araujo@example.com', '20/05/1993'),
(43, 'Sérgio Nascimento', 'sergio.nascimento@example.com', '20/05/1996'),
(44, 'Tamires Cardoso', 'tamires.cardoso@example.com', '20/05/1998'),
(45, 'Valentina Dias', 'valentina.dias@example.com', '20/05/2001'),
(46, 'Wagner Figueiredo', 'wagner.figueiredo@example.com', '20/05/1992'),
(47, 'Ximena Santana', 'ximena.santana@example.com', '20/05/1995'),
(48, 'Yuri Cunha', 'yuri.cunha@example.com', '20/05/1997'),
(49, 'Zélia Silveira', 'zelia.silveira@example.com', '20/05/1993'),
(50, 'Amanda Carvalho', 'amanda.carvalho@example.com', '20/05/2002');

