-- MySQL Script generated by MySQL Workbench
-- Fri May 17 21:58:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema crud_java
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crud_java
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crud_java` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `crud_java` ;

-- -----------------------------------------------------
-- Table `crud_java`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crud_java`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Idade` VARCHAR(20) NULL DEFAULT NULL,
  `Endereco` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Dados Gerados Via ChatGPT 

INSERT INTO `usuarios` (`id`, `Nome`, `Email`, `Idade`, `Endereco`) VALUES
(1, 'Ana Silva', 'ana.silva@example.com', '20/05/1996', 'Rua 3 - Anil - São Luis - MA'),
(2, 'Bruno Costa', 'bruno.costa@example.com', '20/05/1990', 'Av. das Flores - Jardim - Belo Horizonte - MG'),
(3, 'Carla Mendes', 'carla.mendes@example.com', '20/05/2002', 'Rua dos Girassóis - Sol Nascente - Goiânia - GO'),
(4, 'Daniel Souza', 'daniel.souza@example.com', '20/05/1993', 'Av. Principal - Central - Manaus - AM'),
(5, 'Eduardo Lima', 'eduardo.lima@example.com', '20/05/1999', 'Rua das Palmeiras - Paraíso - Salvador - BA'),
(6, 'Fernanda Alves', 'fernanda.alves@example.com', '20/05/1997', 'Av. dos Ipês - Jardim - Campo Grande - MS'),
(7, 'Gustavo Pereira', 'gustavo.pereira@example.com', '20/05/1994', 'Rua 7 - Primavera - Brasília - DF'),
(8, 'Helena Martins', 'helena.martins@example.com', '20/05/1995', 'Av. Central - Novo Horizonte - Recife - PE'),
(9, 'Igor Rocha', 'igor.rocha@example.com', '20/05/2001', 'Rua das Acácias - Vale Verde - Florianópolis - SC'),
(10, 'Juliana Duarte', 'juliana.duarte@example.com', '20/05/1998', 'Av. das Águas - Atlântico - João Pessoa - PB'),
(11, 'Karla Ferreira', 'karla.ferreira@example.com', '20/05/2000', 'Rua das Flores - Centro - Porto Alegre - RS'),
(12, 'Lucas Barbosa', 'lucas.barbosa@example.com', '20/05/1992', 'Av. das Avenidas - Alameda - Teresina - PI'),
(13, 'Mariana Gomes', 'mariana.gomes@example.com', '20/05/1996', 'Rua dos Pinheiros - Boa Vista - Vitória - ES'),
(14, 'Nicolas Fernandes', 'nicolas.fernandes@example.com', '20/05/1991', 'Av. das Oliveiras - Parque - Natal - RN'),
(15, 'Olivia Castro', 'olivia.castro@example.com', '20/05/1997', 'Rua das Pedras - Pedra Lisa - São Paulo - SP'),
(16, 'Paulo Ribeiro', 'paulo.ribeiro@example.com', '20/05/1989', 'Av. dos Coqueiros - Orla - Maceió - AL'),
(17, 'Quésia Moraes', 'quesia.moraes@example.com', '20/05/2000', 'Rua das Margaridas - Jardim - Florianópolis - SC'),
(18, 'Ricardo Araujo', 'ricardo.araujo@example.com', '20/05/1994', 'Av. das Amendoeiras - Parque - Campo Grande - MS'),
(19, 'Sofia Nascimento', 'sofia.nascimento@example.com', '20/05/2002', 'Rua das Violetas - Violeta - Belém - PA'),
(20, 'Thiago Cardoso', 'thiago.cardoso@example.com', '20/05/1993', 'Av. dos Ipês - Centro - Cuiabá - MT'),
(21, 'Ursula Dias', 'ursula.dias@example.com', '20/05/1998', 'Rua do Sol - Sol Nascente - Goiânia - GO'),
(22, 'Victor Figueiredo', 'victor.figueiredo@example.com', '20/05/1995', 'Av. das Acácias - Acácia - Curitiba - PR'),
(23, 'Wesley Santana', 'wesley.santana@example.com', '20/05/1996', 'Rua das Mangueiras - Mangueira - Recife - PE'),
(24, 'Xavier Cunha', 'xavier.cunha@example.com', '20/05/1992', 'Av. da Praia - Beira Mar - Aracaju - SE'),
(25, 'Yara Silveira', 'yara.silveira@example.com', '20/05/2001', 'Rua dos Lírios - Jardim - Porto Alegre - RS'),
(26, 'Zeca Moura', 'zeca.moura@example.com', '20/05/1990', 'Av. das Rosas - Rosa - Fortaleza - CE'),
(27, 'Alice Carvalho', 'alice.carvalho@example.com', '20/05/2002', 'Rua das Hortênsias - Hortênsia - João Pessoa - PB'),
(28, 'Bruno Santos', 'bruno.santos@example.com', '20/05/1991', 'Av. das Dálias - Dália - Curitiba - PR'),
(29, 'Carolina Rocha', 'carolina.rocha@example.com', '20/05/1997', 'Rua das Orquídeas - Orquídea - Brasília - DF'),
(30, 'Diego Ferreira', 'diego.ferreira@example.com', '20/05/1993', 'Av. das Palmas - Palmeiras - Campo Grande - MS'),
(31, 'Eduarda Lima', 'eduarda.lima@example.com', '20/05/1999', 'Rua das Flores - Flor - Belém - PA'),
(32, 'Felipe Alves', 'felipe.alves@example.com', '20/05/1995', 'Av. dos Pinheiros - Pinheiro - Goiânia - GO'),
(33, 'Gabriela Martins', 'gabriela.martins@example.com', '20/05/1998', 'Rua das Cerejeiras - Cerejeira - Porto Alegre - RS'),
(34, 'Heitor Pereira', 'heitor.pereira@example.com', '20/05/1996', 'Av. das Glicínias - Glicínia - Florianópolis - SC'),
(35, 'Isabela Duarte', 'isabela.duarte@example.com', '20/05/2000', 'Rua dos Jasmins - Jasmim - Recife - PE'),
(36, 'João Barbosa', 'joao.barbosa@example.com', '20/05/1992', 'Av. das Acácias - Acácia - Vitória - ES'),
(37, 'Larissa Gomes', 'larissa.gomes@example.com', '20/05/1994', 'Rua das Violetas - Violeta - São Paulo - SP'),
(38, 'Marcos Fernandes', 'marcos.fernandes@example.com', '20/05/1997', 'Av. das Orquídeas - Orquídea - Porto Alegre - RS'),
(39, 'Natália Castro', 'natalia.castro@example.com', '20/05/1999', 'Rua dos Girassóis - Jardim - Curitiba - PR'),
(40, 'Otávio Ribeiro', 'otavio.ribeiro@example.com', '20/05/1991', 'Av. dos Lírios - Lírio - Belo Horizonte - MG'),
(41, 'Patrícia Moraes', 'patricia.moraes@example.com', '20/05/2000', 'Rua das Margaridas - Margarida - Porto Alegre - RS'),
(42, 'Renato Araujo', 'renato.araujo@example.com', '20/05/1993', 'Av. das Hortênsias - Hortênsia - Manaus - AM'),
(43, 'Sérgio Nascimento', 'sergio.nascimento@example.com', '20/05/1996', 'Rua dos Jasmins - Jasmim - Rio de Janeiro - RJ'),
(44, 'Tamires Cardoso', 'tamires.cardoso@example.com', '20/05/1998', 'Av. das Palmeiras - Palmeira - Florianópolis - SC'),
(45, 'Valentina Dias', 'valentina.dias@example.com', '20/05/2001', 'Rua das Cerejeiras - Cerejeira - São Paulo - SP'),
(46, 'Wagner Figueiredo', 'wagner.figueiredo@example.com', '20/05/1992', 'Av. das Glicínias - Glicínia - Belo Horizonte - MG'),
(47, 'Ximena Santana', 'ximena.santana@example.com', '20/05/1995', 'Rua das Acácias - Acácia - Porto Alegre - RS'),
(48, 'Yuri Cunha', 'yuri.cunha@example.com', '20/05/1997', 'Av. das Orquídeas - Orquídea - Brasília - DF'),
(49, 'Zélia Silveira', 'zelia.silveira@example.com', '20/05/1993', 'Rua das Violetas - Violeta - Salvador - BA'),
(50, 'Amanda Carvalho', 'amanda.carvalho@example.com', '20/05/2002', 'Av. dos Girassóis - Jardim - Recife - PE');

